### ISSUE TITLE
sharp-sign (#) filtered out in pronounce.py

### ISSUE THREAD

**Issue by waebbl** [AllenDowney/ThinkPython2#101]
In https://github.com/AllenDowney/ThinkPython2/blob/master/code/pronounce.py#L31 the pronounciation of the sharp-sign from line 57 of c06d is removed as well. Comments in the pronounciation file always start with `##`.

**Comment by AllenDowney** [comment]
Fixed. Thanks for letting me know!

**Comment by waebbl** [comment]
Thanks for fixing it. However, now the last (empty) line of the comment block at the beginning isn't filtered out. I've found, that a solution like `if line[0:2] == '##': continue` gives a correct result.
