### ISSUE TITLE
Some punctuation, not sure it's a bug or just a habit of expression

### ISSUE THREAD

**Issue by wenbindu** [AllenDowney/ThinkPython2#103]
the line : 7253.

`
``I was driving on the highway the other day and I happened to
notice my odometer. Like most odometers, it shows six digits,
in whole miles only. So, if my car had 300,000
miles, for example, I'd see 3-0-0-0-0-0.

``Now, what I saw that day was very interesting. I noticed that the
last 4 digits were palindromic; that is, they read the same forward as
backward. For example, 5-4-4-5 is a palindrome, so my odometer
could have read 3-1-5-4-4-5.

``One mile later, the last 5 numbers were palindromic. For example, it
could have read 3-6-5-4-5-6.  One mile after that, the middle 4 out of
6 numbers were palindromic.  And you ready for this? One mile later,
all 6 were palindromic!

``The question is, what was on the odometer when I first looked?''
`

Dr, @AllenDowney  I am just not sure, if u lost the end of the double quotations for the three paragraphs?

**Comment by AllenDowney** [comment]
Apparently that's standard punctuation for a multi-paragraph quotation. But for the next edition I have a better option. Thanks!
