### ISSUE TITLE
do_four.py IS WRONG 

### ISSUE THREAD

**Issue by Srjuanfra** [AllenDowney/ThinkPython2#106]
in that document is supposed that in function "do_twice" you call the function "print_twice" not just "print"

**Comment by Watynecc** [comment]
Dude just the exercice is a bad practice why not using loops ???

**Comment by espinoza** [comment]
> Dude just the exercice is a bad practice why not using loops ???

Of course. But this exercise is introduced before loops.

**Comment by AllenDowney** [comment]
Right, the intent is to practice using the features we have so far -- and especially to practice writing functions and calling them.

But it's not a great exercise. I'm cutting it from the third edition.

**Comment by Watynecc** [comment]
I think it's better after the loop but when I think about it. It kinda
learned me how to do simple graphics the fact i didn't have access to loop
make it more confused

Le ven. 23 juin 2023, 23:37, Jorge Espinoza ***@***.***> a
écrit :
