### ISSUE TITLE
simple grid.py

### ISSUE THREAD

**Issue by GarageTech** [AllenDowney/ThinkPython2#108]
def half_line(s1, s2):
    print(s1, end=' ')
    print((s2 + ' ') * 4, end='')

def print_line(s1, s2):
    half_line(s1, s2)
    half_line(s1, s2)
    print(s1)

def print_four(s1, s2):
    print_line(s1, s2)
    print_line(s1, s2)
    print_line(s1, s2)
    print_line(s1, s2)

print_line('+', '-')
print_four('|', ' ')
print_line('+', '-')
print_four('|', ' ')
print_line('+', '-')

**Comment by AllenDowney** [comment]
Thanks!
