### ISSUE TITLE
Production: align equation arrays

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkPython2#11]
Page 86

Page 89

**Comment by AllenDowney** [comment]
Now pages 69 and 72

**Comment by kristenORM** [comment]
Now pages 66 and 68, alignment is fixed in latest PDF build. If there are any others that need the same treatment, let me know!

**Comment by AllenDowney** [comment]
Looks good.  In the equation array on page 72, it might be good to left
justify both columns and line up the if's.

But it's not critical.

**Comment by kristenORM** [comment]
Ah, forgot that one. How is this?
![ackermann](https://cloud.githubusercontent.com/assets/1178372/10911339/66072344-8212-11e5-9843-19f36a203b3b.png)

**Comment by AllenDowney** [comment]
Looks great.

Again, if we're being super picky, a little space to the right of the
bracket would be good.

But not critical.
