### ISSUE TITLE
Production: Bigger summation sign

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkPython2#12]
Page 103

**Comment by AllenDowney** [comment]
Now page 83

**Comment by kristenORM** [comment]
Allen, we've increased the size of the summation sign as shown here:
![summation](https://cloud.githubusercontent.com/assets/1178372/10702397/77562de4-7997-11e5-8c3f-efd37f208007.png)

Does this look right, or does the size need to change more? And is this the only instance in the book? Our CSS team tweaked just this one, but can go to Tools for a global fix if the symbol should be larger across the board.

**Comment by AllenDowney** [comment]
That's better, but ideally k=0 should be below the summation and infinity
above.

[image: Inline image 2]
That is the only summation in the book, so no need for a global fix.

But when we get to Think DSP, we have some work to do!

**Comment by kristenORM** [comment]
Here's the latest iteration: how does this look?
![summation_new](https://cloud.githubusercontent.com/assets/1178372/10910691/d2cfe924-820e-11e5-9e90-bcd21c24a72e.png)

**Comment by AllenDowney** [comment]
Looks good.

If we have fine-grain control, I would reduce the stroke weight of the
Sigma and increase the space between the Sigma and k=0.

But it's fine.
