### ISSUE TITLE
no need for icons on page xiii

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkPython2#13]
This book doesn't use any of the icons on page xiii -- can we drop them?

**Comment by kristenORM** [comment]
Sure, I can take those out. The only caveat would be if we decide to use one of them for the Python 2 notes mentioned in an earlier issue. We'd have to use one of those icons, and could add a title to it of your choosing (unless you want to let it go as you suggested on the other issue)

**Comment by AllenDowney** [comment]
No, I'm pretty much settled on not marking the Python 2 sections.  So I'll close this issue.
