### ISSUE TITLE
Section 5.14 - Exercise 1

### ISSUE THREAD

**Issue by AlJohri** [AllenDowney/ThinkPython2#18]
> Exercise 1  
> The time module provides a function, also named time, that returns the current Greenwich Mean Time in “the epoch”, which is an arbitrary time used as a reference point. On UNIX systems, the epoch is 1 January 1970.
> 
> ```
> >> import time
> >> time.time()
> 1437746094.5735958
> ```
> 
> Write a script that reads the current time and converts it to a time of day in hours, minutes, and seconds, plus the number of days since the epoch.

---

I think asking a student to convert the epoch into time of day might be a little too complicated for Exercise 1 of the chapter. Dates aren't the easiest subject to deal with this early into python. I was trying to use ThinkPython 2 to tutor a student today and found it to be far too advanced having just learned conditionals and floor division in the same chapter.

``` python
>>> # Part 1

>>> mydate = int(1437746094.5735958)
>>> num_days = mydate // 3600 // 24
>>> print(num_days, "days since epoch")

16640 days since epoch

>>> # Part 2

>>> midnight_on_mydate = num_days * 24 * 3600
>>>
>>> seconds_since_midnight = mydate - midnight_on_mydate
>>>
>>> hours = seconds_since_midnight // 3600
>>> minutes = (seconds_since_midnight - (hours * 3600)) // 60
>>> seconds = seconds_since_midnight - (hours * 3600 + minutes * 60)
>>>
>>> time_of_day = "%s:%s:%s" % (hours, minutes, seconds)
>>>
>>> print(time_of_day, "on", num_days, "days since epoch")

13:54:54 on 16640 days since epoch
```

**Comment by JCWDFCS** [comment]
```python
import time

epoch = time.time()
seconds_in_a_day = 24 * 60 * 60
seconds_in_an_hour = 60 * 60
seconds_in_a_minute = 60

days = epoch // seconds_in_a_day
hours = (epoch % seconds_in_a_day) // seconds_in_an_hour + 8
minutes = (epoch % seconds_in_a_day) % seconds_in_an_hour // seconds_in_a_minute
seconds = (epoch % seconds_in_a_day) % seconds_in_an_hour % seconds_in_a_minute
print("%s: %s: %s: %s" %(days, hours, minutes, seconds))
print("Beijing Current time is %d: %d: %d: %d" %(days, hours, minutes, seconds")) ```

**Comment by AndrewReifel** [comment]
Looks like an extra closing quote is not needed on final print statement.

**Comment by Janardanchorat** [comment]
`import time
mytime=time.time()
seconds=mytime
mins=mytime/60
hrs=mins/60
days=hrs/24
weeks=days/7
months=weeks/4
years=months/12
print(seconds,mins,hrs,days,weeks,months,years)`

**Comment by neo-shruti-ghosh** [comment]
>>>import time


>>>epoch=time.time()

>>>#60*60*24=86400
>>>total_sec = epoch % 86400
>>>#60*60
>>>hours = int(total_sec/3600)
>>>total_minutes = int(total_sec/60)
>>>mins = total_minutes % 60
>>>sec = int(total_sec % 60)

>>>days=int(epoch/86400)

>>>print("The Current time is",hours,':',mins,':',sec)
>>>print("Days since epoch:", days)

**Comment by ohokusan** [comment]
My first draft, I'm a complete beginner.

```python
import time

current_time = int(time.time()) # in seconds

# epochs in seconds, thereby everything should be in the same units to evaluate
seconds_in_a_day = 60 * 60 * 24
days = current_time // seconds_in_a_day

seconds_remainder = current_time % seconds_in_a_day

seconds_in_an_hour = 60 * 60
hours = seconds_remainder // seconds_in_an_hour

seconds_remainder = seconds_remainder % seconds_in_an_hour

seconds_in_a_minute = 60
minutes = seconds_remainder // seconds_in_a_minute
seconds = seconds_remainder % seconds_in_a_minute

print(days, hours, minutes, seconds)
```

I then attempted to refactor it to practice recursion, keyword arguments and conditional statements, as outlined in the chapter with the exercise:
```python
import time

seconds_in_a_day = 60 * 60 * 24
seconds_in_an_hour = 60 * 60
seconds_in_a_minute = 60

def time_detect(time_in_sec, days=0, hours=0, minutes=0):
  if days == 0:
    days = time_in_sec // seconds_in_a_day
    remainder = time_in_sec % seconds_in_a_day
    print(days, "days,", end=" ")
    time_detect(remainder, days)
  elif hours == 0:
    hours = time_in_sec // seconds_in_an_hour
    remainder = time_in_sec % seconds_in_an_hour
    print(hours, "hours,", end=" ")
    time_detect(remainder, days, hours)
  elif minutes == 0:
    minutes= time_in_sec // seconds_in_a_minute
    remainder = time_in_sec % seconds_in_a_minute
    print(minutes, "minutes,", end=" ")
    time_detect(remainder, days, hours, minutes)
  else:
    print(time_in_sec, "seconds")

time_detect(int(time.time()))
```
