### ISSUE TITLE
... not legal ... but legal.

### ISSUE THREAD

**Issue by Arya766** [AllenDowney/ThinkPython2#20]
Inexpressively written:

Page 4, title no. 1.5, 2nd paragraph from the end.

Thanks

**Comment by AllenDowney** [comment]
It's not a legal *integer*, but it is a legal expression.

I'm not sure I understand your suggestion.  Can you say more about what
should be clarified?

**Comment by Arya766** [comment]
Yes, it's not clear for those like me, whose maternal language is not English, and have all struggles of a noob. It would be way more comprehensible should you add the above said "expression".
Thanks again

**Comment by AllenDowney** [comment]
I understand.  I wanted to, but at this point in the book, "expression" has
not been defined yet.

**Comment by Arya766** [comment]
Good point! Didn't notice that. Well, thank you for making it clear to me. And thanks for responding to questions like mine.

**Comment by Arya766** [comment]
Good point! Didn't notice that. Well, thank you for making it clear to me. And thanks for responding to questions like mine.
