### ISSUE TITLE
Identical or Misunderstood?

### ISSUE THREAD

**Issue by Arya766** [AllenDowney/ThinkPython2#21]
Page 7, Title 1.9 Exercises:

Exercise1.1.

Are exercises 1 & 2 the same, or did I miss something?
Thanks

**Comment by AllenDowney** [comment]
I'll investigate...

**Comment by calcisme** [comment]
The two questions are similar, but not identical.
Exercise 1 asks what happens if you leave out a parenthesis (or both).
Exercise 2 asks what happens if you leave out a quotation mark (or both).
