### ISSUE TITLE
super() missing?

### ISSUE THREAD

**Issue by Kwpolska** [AllenDowney/ThinkPython2#27]
Hi,
the book has [an entire chapter](http://greenteapress.com/thinkpython2/html/thinkpython2019.html) about Inheritance, but I noticed it lacks a mention of `super()`. Being able to use code of the parent function is, in my opinion, a pretty useful thing to do. Could you consider adding that?

**Comment by AllenDowney** [comment]
Hi Chris,

This is a good suggestion, and it would be good for readers to know about.

But the mechanism for calling super() in Python is a little tough to
swallow for beginners, so I opted for naming the parent explicitly.  That's
not the most Pythonic choice, but I think it's the right compromise for the
audience I am aiming at.

Thanks!
Allen
