### ISSUE TITLE
Two markov.py files w/different filename casing cause git for Windows confusion: Markov.py and markov.py

### ISSUE THREAD

**Issue by mdweber** [AllenDowney/ThinkPython2#36]
Steps:
1. User forks AllenDowney/ThinkPython2 to their GitHub
2. User clones their new ThinkPython2 fork from their GitHub to their local Windows PC.
3. Local git clients (git-gui, git-bash, GitHub Desktop) all say there are un-staged edits to code/Markov.py even though the user has made no changes (or even opened one of the files):
![image](https://user-images.githubusercontent.com/28764003/35135321-1e080006-fca2-11e7-87ee-891e416dc87b.png)
![gitstatus](https://user-images.githubusercontent.com/28764003/35135312-063f1d06-fca2-11e7-9ae2-55c9f2b39401.png)

Cause:
It is not obvious when looking at the files in GitHub or Windows explorer, but there are two Markov.py files in the code folder (one starting with an uppercase M and the other with a lower m).  The contents of the two files are different.  You can see it when you download and open the .zip from GitHub (for some reason windows has no problem listing both files when viewing the contents of the .zip, but when you extract them one will get overwritten).
![image](https://user-images.githubusercontent.com/28764003/35135436-fb0f53dc-fca2-11e7-8763-8b3f7a7bdd08.png)
One gets overwritten, the other stays.  Git sees it is different than the last commit and marks it as modified.

**Comment by AllenDowney** [comment]
This should be fixed now:
https://github.com/AllenDowney/ThinkPython2/commit/666a2f23c7206925775c114d525acf4eddcffe41
Thanks for letting me know!
