### ISSUE TITLE
Clarification on book license

### ISSUE THREAD

**Issue by learnbyexample** [AllenDowney/ThinkPython2#37]
Hello Sir,

As per https://github.com/AllenDowney/ThinkPython2/blob/master/LICENSE , it is MIT

As per http://greenteapress.com/wp/think-python-2e/ : 

> Think Python 2e is a Free Book. It is available under the Creative Commons Attribution-NonCommercial 3.0 Unported License, which means that you are free to copy, distribute, and modify it, as long as you attribute the work and don’t use it for commercial purposes.

Could you please clarify the purpose of each license? If I fork this repo, should I mention both licenses?

Also, if I am interested in porting the book to Ruby, is it okay?

Thanks,
Sundeep

**Comment by AllenDowney** [comment]
Thanks for asking, and sorry for the confusion.  The code is under the MIT
license; the book is under the CC NonCommercial license.

I'd be delighted if you ported the book to Ruby.  Please send me an email
and let's talk more.

**Comment by learnbyexample** [comment]
Thanks for the clarification..
I've sent an email as well
