### ISSUE TITLE
Any way to convert this book to epub?

### ISSUE THREAD

**Issue by ofou** [AllenDowney/ThinkPython2#39]
I would really love to read it in my e-reader :)

**Comment by jjlwork** [comment]
You can "make hevea" then make "epub" this has all the navigation links, headers and footers from the html version, which is kind of ugly IMO. I made a "cleaner" output in my fork that gets rid of the header, footer and nav links. If you use my fork "make hevea" is not necessary you just need to "make epub"

**Comment by AllenDowney** [comment]
I would like to provide this capability, but I am not sure when I will get
to it.  Sorry!

**Comment by jjlwork** [comment]
Allen just accepted my commit so I guess you can just do it from the main repo now via "make epub". Thanks Allen. I might submit one later for .mobi files as well for the other half of the ebook market. But for now, off to fathers day activities.

**Comment by ofou** [comment]
hey @jjlwork & @AllenDowney thank you very much! 

Have a great day! 👏
