### ISSUE TITLE
Production: boxes around figures

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkPython2#4]
I think the boxes around the figures are unnecessary.
* We can remove them, but boxes are our style, and I see them in the other "Think" books. I'd vote for leaving them be.

**Comment by kristenORM** [comment]
Not sure who left the bulleted note, but they are correct in that the boxes are O'Reilly style and I also vote for leaving them in. Let me know if you strongly disagree, though.

**Comment by AllenDowney** [comment]
Ok.
