### ISSUE TITLE
MD5 commentary is out of date

### ISSUE THREAD

**Issue by marked** [AllenDowney/ThinkPython2#44]
Chapter 14.8  Pipes:

For example, most Unix systems provide a command called md5sum that reads the contents of a file and computes a “checksum”. You can read about MD5 at http://en.wikipedia.org/wiki/Md5. This command provides an efficient way to check whether two files have the same contents. The probability that different contents yield the same checksum is very small (that is, unlikely to happen before the universe collapses).

md5 hash collisions are easily generated now.  Maybe a footnote is warranted?

**Comment by AllenDowney** [comment]
I think it is still true that unintentional collisions are unlikely.
