### ISSUE TITLE
Production: icon to identify Python 2 

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkPython2#6]
Can we get a Python 2 icon to mark the places where I discuss Python 2?  (There are only 4-5 of them)
* What should the icon look like? Doable, but we need more guidance on what he's thinking. Maybe a mockup or pointing us to something similar in another title? Sounds doable though.

**Comment by kristenORM** [comment]
Allen, following up on this. What do you imagine the icon should look like? Would text saying "Python 2" work? It will take longer to create a more ornate icon, so want to get a more specific request to Design if that's the route you want to take.

**Comment by AllenDowney** [comment]
It sounds like this might be more trouble than it's worth.  There are only a few examples, and calling them out is not important.  I'll close this issue -- please reopen if you disagree.

**Comment by kristenORM** [comment]
There's one other option that we might pursue, since there are only a few...it's possible to put a title on a note (though may need to use an HTML passthrough to do so):

div data-type="note">
  <h1>Python 2</h1>
  <p>Please take note of this important information...</p>
</div>

**Comment by kristenORM** [comment]
Update: I've been told we can't do passthroughs in XML, but this markup might work (I'd test it but not sure which notes it should be applied to):

```
<note>
<title>My Title</title>
<para>Some text></para>
</note>
```
