### ISSUE TITLE
Production: table on page 264

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkPython2#7]
The table on page 264 needs help (and we should check other tables)"
- We'd do this in production.

**Comment by AllenDowney** [comment]
Now pages 245-6

**Comment by kristenORM** [comment]
believe this is fixed now; each table entry was nested in a ```<para>``` tag, which was causing the extra spacing.

**Comment by AllenDowney** [comment]
Got it.  Looks like it's the same problem with the other tables.  There are 4 tables in the book; can you confirm that you got them all?

**Comment by kristenORM** [comment]
I believe I got them all! Fixed two on page 206, one on pg 244, and one on pg 245. But if we see any more during copyedit, it's an easy fix.

**Comment by AllenDowney** [comment]
Ok, just leaving this open so we check later.
