### ISSUE TITLE
chapter 2 and section 2.5

### ISSUE THREAD

**Issue by wenbindu** [AllenDowney/ThinkPython2#83]
the sentence: I don't work very hard to remember the precedence of operators.
I do not know if I understood the real meaning or what u want to say.
I guess what u want to say is: I know it's very hard to ....

**Comment by AllenDowney** [comment]
I see why this sentence might not be clear. I mean to say that memorizing the precedence of operators is not necessary -- if you write an expression where the order of operations is not obvious, you should use parentheses to make it obvious.

**Comment by wenbindu** [comment]
> I see why this sentence might not be clear. I mean to say that memorizing the precedence of operators is not necessary -- if you write an expression where the order of operations is not obvious, you should use parentheses to make it obvious.

I see. Thanks.
