### ISSUE TITLE
Production: needs the CC copyright notice

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkPython2#9]

**Comment by kristenORM** [comment]
added, but will need to update link to 2E

**Comment by AllenDowney** [comment]
The link goes to the right version, but I would prefer it to go to the landing page http://greenteapress.com/thinkpython2/ rather than directly to the PDF.

**Comment by kristenORM** [comment]
OK, done!

**Comment by Adrianzo** [comment]
By the way, the repo should have a LICENSE file with the actual license here on github. Else, AFAIK the content of the repo is under copyright of its owner.

**Comment by AllenDowney** [comment]
Done.  Thanks!
